version: '1.0'
stages:
  - prepare
  - build
  - deploy
steps:
  clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: Codefresh-training/helm-sample-app
    revision: "${{CF_BRANCH}}"
    git: github
  build:
    title: Building Docker Image
    stage: build
    type: build
    registry: quay
    working_directory: ./helm-sample-app
    image_name: codefresh-training/helm-go-example
    tag: 2.0.0
    dockerfile: Dockerfile
  store:
    title: Storing Helm Chart
    type: helm
    stage: build
    working_directory: ./helm-sample-app
    arguments:
      action: push
      helm_version: 3.0.2
      chart_name: charts/helm-example
      kube_context: training
      chart_repo_url: 'cm://h.cfcr.io/codefresh-training/default'
  deploy:
    type: helm
    stage: deploy
    working_directory: ./helm-sample-app
    arguments:
      action: install
      chart_name: charts/helm-example
      release_name: my-go-chart-prod-<username>
      helm_version: 3.0.2
      kube_context: training
      namespace: <username>
      custom_values:
        - 'buildID=${{CF_BUILD_ID}}'
        - 'image_pullPolicy=Always'
        - 'image_tag=2.0.0'
        - 'replicaCount=2'
